// CharacterEditablePop Component
//
// This component manages the full character editing and creation workflow inside a project.
// It allows users to view, add, edit, and delete characters — both AI-generated and manually created.
// It’s shown as a popup overlay when the user wants to modify characters linked to a specific project.
//
// ------------------------------------------------------------
// Overview
// ------------------------------------------------------------
// - Displays two sections: “Generated by Ida” (AI) and “Added by Me” (user-made).
// - Provides inline editing and adding of characters with proper role-based sorting.
// - Ensures the order of characters follows a predefined logical sequence (e.g., Protagonist, Antagonist, Sidekick, etc.).
// - Integrates with character-related API endpoints to fetch, delete, and update character data.
// - Offers access control checks before allowing a new character to be added.
//
// ------------------------------------------------------------
// Core Logic
// ------------------------------------------------------------
//
// 1. **Fetching & Initialization**
//    - Loads character data from the backend using `useGetSavedCharactersQuery`.
//    - When fetched, stores them locally in `characterArray` and `duplicateCharacterArray` for change tracking.
//    - If it’s not an old project, automatically triggers `characterRefetch()` on mount or project ID change.
//    //! Important: Keeps character data in sync between frontend edits and backend updates.
//
// 2. **Sorting & Display**
//    - Uses a fixed `characterOrder` array to display characters in a meaningful hierarchy.
//    - Characters not found in that order are appended at the end.
//    - Divides the final list into two groups: AI-generated and user-created.
//
// 3. **Edit / Delete / Add Flows**
//    - `handleEditClick()` opens a popup to modify existing character data.
//    - `handleSaveEditedCharacter()` updates the edited item in local state and closes the popup.
//    - `deleteCharacterFun()` handles character deletion both locally and via API if the character has an ID.
//    - `handleAddNewCharacter()` appends new character entries to the list dynamically.
//    //! Important: Maintains immutability — character arrays are always updated using copies.
//
// 4. **User Access & Permissions**
//    - Before adding a new character, checks user privileges via `fetchUserAccess()`.
//    - If the user doesn’t have permission, shows a “No Access” popup (handled by `NoAccessPopUp`).
//    - Otherwise, opens the add-character popup (`SingleCharacterAdd`).
//    //! Important: Prevents unauthorized access to premium or restricted features.
//
// 5. **Confirmation & Saving**
//    - “Save Character” and “Save as Draft” buttons handle two different flows:
//        • Save Character → finalizes and locks edits.
//        • Save as Draft → temporarily stores without locking edits.
//    - Includes a user confirmation checkbox before final save to ensure users understand restrictions.
//    //! Important: Prevents accidental lock-in of characters before user confirmation.
//
// 6. **UI / UX Behavior**
//    - Renders as a modal overlay with responsive design for desktop and mobile.
//    - Includes draggable and scrollable sections for better usability on smaller screens.
//    - Integrates short demo popups (`AddCharDemoPop`) shown only once using localStorage flags.
//
// ------------------------------------------------------------
// Props Overview
// ------------------------------------------------------------
// - setCharacterEditPop: Controls visibility of this popup.
// - characterArray / setCharacterArray: Main state for managing character data.
// - currentProjectData: Info about the current project (used for labels and context).
// - handleUpdateSavedChar: Triggers saving the current character set.
// - handleSaveAsDraft: Saves the current state as a draft.
// - characterLoading: Indicates loading state during API calls.
// - onlyAdd: Controls if the popup is in “Add-only” mode (no edits).
// - is_draft: Indicates if the current project is still a draft.
// - openOnSaveCharactersDemoPop / setOpenOnSaveCharactersDemoPop: Controls tutorial popup visibility.
// - setPreviewAfterDraft, setOpenCharacterChart, refetch, fromNew: Utility callbacks for state updates.
//
// ------------------------------------------------------------
// Summary
// ------------------------------------------------------------
// CharacterEditablePop is the central place for managing all character interactions in a project.
// It provides a well-structured way to add, modify, delete, or confirm characters —
// while respecting user permissions and preventing data loss.
//
// //! Key takeaway: This component ensures a stable, guided, and permission-aware
//    experience for managing both AI-generated and user-created story characters.

import { useContext, useEffect, useState } from "react";
import { FaPlus } from "react-icons/fa";
import { MdOutlineKeyboardBackspace } from "react-icons/md";
import { fetchUserAccess, MyContext } from "../../../App";
import {
  useDeleteCharacterMutation,
  useGetSavedCharactersQuery,
} from "../../../app/EndPoints/Characters/Characters";
import AddCharDemoPop from "../../PremiseV2/sequalPopup/singlePop/AddCharDemoPop";
import { getTextFromValue } from "../../PremiseV2/utilityFuncitons/functions";
import NoAccessCreditPopupUpdate from "../../PricingModel/NoAccessCreditPopupUpdate";
import CharacterShowCard from "./Card";
import SingleCharacterAdd from "./SingleCharacterAdd";
import SingleCharacterEdit from "./SingleCharacterEdit";

const CharacterEditablePop = ({
  setCharacterEditPop,
  characterArray,
  currentProjectData,
  // characters,
  // setCharacters,
  handleUpdateSavedChar,
  handleSaveAsDraft,
  setCharacterArray,
  characterLoading,
  onlyAdd,
  project_id,
  source_language,
  isOldProject,
  openOnSaveCharactersDemoPop,
  setOpenOnSaveCharactersDemoPop,
  is_draft,
  setPreviewAfterDraft,
  setOpenCharacterChart,
  refetch,
  fromNew,
}) => {
  const [modifiedCharacters, setModifiedCharacters] = useState([]);

  const { currentUser } = useContext(MyContext);

  const [editPopupOpen, setEditPopupOpen] = useState(false);
  const [addNewCharacter, setAddNewCharacter] = useState(null);
  const [editData, setEditData] = useState({});
  const [editIdx, setEditIdx] = useState(null);
  const [deleteIdx, setDeleteIdx] = useState(null);
  const [deleteChar, setDeleteChar] = useState(null);
  const [duplicateCharacterArray, setDuplicateCharacterArray] = useState([]);
  const [saveCheckUser, setSaveCheckUser] = useState(false);

  const [deleteCharacter] = useDeleteCharacterMutation();

  const characterOrder = [
    "Protagonist",
    "Antagonist",
    "Co-Star",
    "Antagonist's Right Hand",
    "Love Interest",
    "Rival",
    "Sidekick",
    "Comic Relief",
    "Narrator",
    "Mediator",
    "Confidant",
    "Foil",
    "Mentor",
    "Symbolic Character",
    "Suspect",
    "Family Member",
    "Instigator",
    "Authority Figure",
    "Activist",
    "Peer",
    "Seeker ",
    "Guardian",
    "Supporting Character",
    "Expert",
    "Arbiter",
  ];

  const sortedCharacters = characterOrder?.reduce((acc, role) => {
    const filteredChars =
      characterArray?.filter((char) => char.role === role) || [];
    return acc.concat(filteredChars);
  }, []);

  // Add characters with roles not in the roleOrder array
  const remainingCharacters = characterArray
    ? characterArray.filter((char) => !characterOrder?.includes(char.role))
    : [];

  // Concatenate the remaining characters to the sorted list
  const finalCharacters = [...sortedCharacters, ...remainingCharacters];

  const finalAICharacters = [
    ...sortedCharacters,
    ...remainingCharacters,
  ].filter((char) => char?.is_ai_generated);
  const finalByMeCharacters = [
    ...sortedCharacters,
    ...remainingCharacters,
  ].filter((char) => !char?.is_ai_generated);

  const {
    data: characters,
    isCharLoading,
    isError,
    refetch: characterRefetch,
  } = useGetSavedCharactersQuery(project_id, {
    skip: isOldProject,
  });

  useEffect(() => {
    if (characters) {
      setCharacterArray(characters);
      setDuplicateCharacterArray(characters);
    }
  }, [characters]);

  useEffect(() => {
    if (!isOldProject && project_id) {
      characterRefetch();
    }
  }, [project_id, isOldProject]);

  const handleEditClick = (character) => {
    setEditPopupOpen(true);
    setEditData(character);
  };
  const handleSaveEditedCharacter = (updatedCharacter, index) => {
    const updatedCharacters = characterArray.map((char, i) =>
      i === index ? updatedCharacter : char
    );
    setCharacterArray(updatedCharacters);
    // console.log(updatedCharacters);
    setEditPopupOpen(false); // Close the popup after saving
  };

  // const handleDeleteCharacter = () => {
  //   const updatedCharacters = characterArray.filter(
  //     (char) => char.role !== deleteChar
  //   );
  //   setCharacterArray(updatedCharacters);
  //   console.log("After Deletion:", updatedCharacters);
  // };

  const handleDeleteCharacter = (role) => {
    console.log(role);

    const updatedCharacters = characterArray.filter(
      (char) => char.role !== role
    );
    setCharacterArray(updatedCharacters);
    // console.log("After Deletion:", updatedCharacters);
  };
  const deleteCharacterFun = async (character) => {
    if (character?.id) {
      const res = await deleteCharacter(character?.id);
      if (res) {
        characterRefetch();
      }
    } else {
      const updatedCharacters = characterArray.filter(
        (char) => char.role !== character?.role
      );
      setCharacterArray(updatedCharacters);
    }
  };
  const handleAddNewCharacter = (newCharacter) => {
    const updatedCharacters = [...characterArray, newCharacter];
    // console.log("After Adding New Character:", updatedCharacters);
    setCharacterArray(updatedCharacters);
  };

  // const options = {
  //   "Short film": [
  //     { text: "About 2 Minutes", value: "Upto 2 Minutes" },
  //     { text: "About 5 Minutes", value: "2 to 4 Minutes" },
  //     { text: "About 15 Minutes", value: "5 to 14 Minutes" },
  //     { text: "About 25 Minutes", value: "15 to 29 Minutes" },
  //     { text: "About 30 Minutes", value: "30 Minutes" },
  //   ],
  //   "Feature film": [
  //     { text: "About 1 Hour", value: "1 Hour" },
  //     { text: "About 2 Hours", value: "2 Hours" },
  //     { text: "About 3 Hours", value: "3 Hours" },
  //   ],
  // };

  // const getTextFromValue = (value) => {
  //   for (const category in options) {
  //     const foundOption = options[category].find(
  //       (option) => option.value === value
  //     );
  //     if (foundOption) {
  //       return foundOption.text;
  //     }
  //   }
  //   return value;
  // };

  const handleClosePopup = () => {
    if (characterArray > duplicateCharacterArray) {
      const confirm = window.confirm("Your changes may not be saved!");
      if (confirm) {
        setCharacterEditPop(false);
      } else {
        return;
      }
    } else {
      setCharacterEditPop(false);
    }
  };

  const [openAddCharDemoPop, setOpenAddCharDemoPop] = useState(false);

  const handleAddNewChar = async () => {
    const addCharDemoPop = localStorage.getItem("addNewCharDemoPop");
    if (
      (!addCharDemoPop || addCharDemoPop === "false") &&
      !openAddCharDemoPop
    ) {
      setOpenAddCharDemoPop(true);
    }
    const res = await fetchUserAccess(`PP_AddCharacters`);

    if (res?.access === "No") {
      setAddNewCharacter(res);
    } else {
      setAddNewCharacter("Yes");
    }
  };

  return (
    <div className="fixed top-0 left-0 bottom-0 right-0 w-full h-screen flex items-center bg-[#252525b0] justify-center z-[21]">
      {/* <div className="fixed inset-0 bg-black opacity-50"></div> */}
      <div
        className={`relative ${
          fromNew ? "mt-[-30px]" : "mt-16 "
        } bg-[#fafafa] py-8 md:rounded-lg shadow-lg w-full md:w-[87%] mx-auto lg:w-[950px] h-[91vh] md:h-[500px] `}
      >
        <button
          onClick={handleClosePopup}
          className="absolute hidden md:block right-[-13px] top-[-13px] bg-[#EE3C4D] text-white rounded-full w-8 h-8  items-center justify-center shadow"
        >
          ✕
        </button>
        <div className="mb-[17px] flex pl-2 md:hidden">
          <h3 className="text-center flex  gap-[9px] font-[500]">
            <MdOutlineKeyboardBackspace
              onClick={() => setCharacterEditPop(false)}
              className=" lg:hidden text-[#252525] cursor-pointer h-[36px] w-[36px]"
            />{" "}
          </h3>
          <p className="text-[16px] leading-6  font-semibold mb-[20px] pl-4 ">
            {!onlyAdd && "Proposed"} Characters in about{", "}
            <span className="">
              {getTextFromValue(currentProjectData?.duration)}
            </span>{" "}
            <span className="">{currentProjectData?.nature_project}</span>{" "}
            <span
              data-te-toggle="tooltip"
              title={`${`${currentProjectData?.name} `}`}
              className="notranslate"
            >
              {currentProjectData?.name?.slice(0, 20)}
              {/* {currentProjectData?.name.length > 20
              ? `${currentProjectData?.name.slice(0, 20)}...`
              : currentProjectData} */}
            </span>
          </p>
        </div>

        <h3 className="text-[16px] hidden lg:block font-semibold mb-[20px] px-6 md:px-[56px]">
          {!onlyAdd && "Proposed"} Characters in about{" "}
          <span className="">
            {getTextFromValue(currentProjectData?.duration)}
          </span>{" "}
          <span className="">{currentProjectData?.nature_project}</span>
          {", "}
          <span
            data-te-toggle="tooltip"
            title={`${`${currentProjectData?.name} `}`}
            className="notranslate"
          >
            {currentProjectData?.name?.slice(0, 20)}
            {/* {currentProjectData?.name.length > 20
              ? `${currentProjectData?.name.slice(0, 20)}...`
              : currentProjectData} */}
          </span>
        </h3>

        {/* 3 Column Layout */}
        <div className="h-[calc(90vh-230px)]  overflow-auto md:h-auto md:max-h-[312px] px-6 md:px-[56px]">
          {finalAICharacters?.length > 0 && (
            <p className=" text-[#252525] text-[16px] font-[600] mb-2">
              Generated By Ida
            </p>
          )}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-x-[54px] gap-y-[8px] justify-center">
            {finalAICharacters?.map((character, index) => (
              <CharacterShowCard
                key={index + character?.id}
                index={index + finalAICharacters?.length}
                {...{
                  character,
                  index,
                  setEditData,
                  setEditIdx,
                  setDeleteIdx,
                  setEditPopupOpen,
                  setDeleteChar,
                  onlyAdd,
                  deleteCharacterFun,
                  isAddedByMe: false,
                  source_language,
                  is_draft,
                  duplicateCharacterArray,
                  characterArray,
                  handleUpdateSavedChar,
                }}
              />
            ))}
          </div>

          {finalByMeCharacters?.length > 0 && (
            <p className=" text-[#33B0CA] text-[16px] font-[600] mt-3 mb-2">
              Added By Me
            </p>
          )}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-x-[54px] gap-y-[8px] justify-center ">
            {finalByMeCharacters?.map((character, index) => (
              <CharacterShowCard
                key={index + character?.id}
                index={index + finalAICharacters?.length}
                {...{
                  character,
                  setEditData,
                  setEditIdx,
                  setDeleteIdx,
                  setEditPopupOpen,
                  setDeleteChar,
                  onlyAdd,
                  deleteCharacterFun,
                  isAddedByMe: true,
                  source_language,
                  is_draft,
                  duplicateCharacterArray,
                  characterArray,
                  handleUpdateSavedChar,
                }}
              />
            ))}
          </div>
        </div>
        {/* {console.log(characterArray)} */}
        {!onlyAdd && (
          <div className="flex md:mx-10 justify-between pl-2 gap-[16px] mt-6 md:mt-0 md:absolute bottom-[68px] right-[30px] md:bottom-[15px]">
            <label className="flex custom-checkbox items-start gap-2 cursor-pointer">
              <input
                type="checkbox"
                checked={saveCheckUser}
                onChange={() => setSaveCheckUser(!saveCheckUser)}
                className="w-4 h-4 mt-1 shrink-0 noAccessRadio"
              />
              <span className="text-[12px] leading-snug md:w-[58%] pr-4">
                I understand that after saving this character list: <br />
                1. I will not be able to edit these characters.
                <br />
                2. I will, however, be able to view or delete any character and
                also add more characters (This can be done from the 'Show
                Characters' icon on the script pad or Brainstorm page of the
                associated Premise).
              </span>
            </label>
          </div>
        )}

        {/* Bottom Buttons */}
        <div className="md:absolute px-4 right-[30px] bottom-[30px] flex justify-end gap-[16px] mt-[38px]">
          {finalCharacters?.length <= 17 && (
            <button
              onClick={handleAddNewChar}
              className="bg-[#fafafa] flex items-center gap-[10px] justify-center text-[14px] text-[#33B0CA] border border-[#33B0CA] w-[145px] h-[32px] rounded-[8px] "
            >
              <FaPlus /> <span>Add Character</span>
            </button>
          )}
          {!onlyAdd ? (
            <>
              {saveCheckUser ? (
                <>
                  {is_draft ? (
                    <button
                      disabled={!saveCheckUser || characterLoading}
                      onClick={async () => {
                        await handleUpdateSavedChar();
                        setPreviewAfterDraft(true);
                        // setOpenCharacterChart(false);
                      }}
                      className={`${
                        saveCheckUser ? "bg-[#33B0CA]" : "bg-[#ACDDE7]"
                      } text-white px-3 h-[32px] text-[14px] font-[600] rounded-[8px]`}
                    >
                      Save Character
                    </button>
                  ) : (
                    <button
                      disabled={!saveCheckUser || characterLoading}
                      onClick={async () => {
                        await handleUpdateSavedChar();
                        setOpenCharacterChart(false);
                      }}
                      className={`${
                        saveCheckUser ? "bg-[#33B0CA]" : "bg-[#ACDDE7]"
                      } text-white px-3 h-[32px] text-[14px] font-[600] rounded-[8px]`}
                    >
                      Save Character
                    </button>
                  )}
                </>
              ) : (
                <button
                  // disabled={saveCheckUser || characterLoading}
                  onClick={() => {
                    handleSaveAsDraft();
                  }}
                  className={`${
                    !saveCheckUser ? "bg-[#33B0CA]" : "bg-[#ACDDE7]"
                  } text-white w-[119px] h-[32px] text-[14px] font-[600] rounded-[8px]`}
                >
                  Save As Draft
                </button>
              )}
            </>
          ) : (
            <button
              disabled={characterLoading}
              onClick={async () => {
                await handleUpdateSavedChar();
                // setOpenCharacterChart(false);
              }}
              className={`${
                !characterLoading ? "bg-[#33B0CA]" : "bg-[#ACDDE7]"
              } text-white px-3 h-[32px] text-[14px] font-[600] rounded-[8px]`}
            >
              Save Character
            </button>
          )}
        </div>
      </div>
      <div>
        {editPopupOpen && (
          <SingleCharacterEdit
            setEditPopupOpen={setEditPopupOpen}
            editData={editData}
            editIdx={editIdx}
            onSave={handleSaveEditedCharacter}
            characterArray={characterArray}
            onlyAdd={onlyAdd}
            isEditPopupOpen={editPopupOpen}
            source_language={source_language}
          />
        )}
      </div>
      <div>
        {addNewCharacter?.has_access === false && (
          <NoAccessCreditPopupUpdate
            noAccessPopup={addNewCharacter}
            setNoAccessPopup={setAddNewCharacter}
            service={"Brainstorming"}
            credit_rate={addNewCharacter?.credit_rate}
            remaining_credits={addNewCharacter?.remaining_credits}
          />
        )}
        {addNewCharacter === "Yes" && (
          <SingleCharacterAdd
            setAddNewCharacter={setAddNewCharacter}
            editData={editData}
            handleAddNewCharacter={handleAddNewCharacter}
            characterArray={characterArray}
            source_language={source_language}
          />
        )}
      </div>

      {openAddCharDemoPop && (
        <AddCharDemoPop popClose={() => setOpenAddCharDemoPop(false)} />
      )}
    </div>
  );
};

export default CharacterEditablePop;
