export const keyboardOptions = [
  // "Afrikaans",
  // "Albanian",
  // "Amharic",
  "Arabic",
  // "Armenian",
  // "Assamese",
  // "Azerbaijani",
  // "Basque",
  "Belarusian",
  "Bengali",
  // "Bosnian",
  // 'Baluchi',
  // "Bulgarian",
  // "Burmese",
  // "Catalan",
  // "Cebuano",
  // "Chinese(Simplified)",
  // "Chinese(Traditional)",
  // "Corsican",
  // "Croatian",
  // "Czech",
  // "Danish",
  "Dutch",
  "English",
  // "Esperanto",
  // "Estonian",
  // "Filipino",
  // "Finnish",
  "French",
  // "Frisian",
  // "Gaelic",
  "Galician",
  // "Georgian",
  "German",
  // "Greek",
  "Gujarati",
  // "Haitian",
  // "Hausa",
  // "Hawaiian",
  // "Hebrew",
  "Hindi",
  // "Hmong",
  // "Hungarian",
  // "Icelandic",
  // "Igbo",
  "Indonesian",
  // "Irish",
  // "Italian",
  // "Japanese",
  // "Javanese",
  "Kannada",
  // "Kazakh",
  // "Khmer",
  // "Kinyarwanda",
  // "Korean",
  // "Kyrgyz",
  // "Lao",
  // "Latin",
  // "Latvian",
  // "Lithuanian",
  // "Luxembourgish",
  // "Macedonian",
  // "Malagasy",
  // "Malay",
  "Malayalam",
  // "Maltese",
  // "Maori",
  "Marathi",
  // "Mongolian",
  // "Myanmar",
  "Nepali",
  // "Norwegian",
  "Oriya",
  // "Pashto",
  // "Persian",
  // "Polish",
  // "Portuguese",
  "Punjabi",
  // "Romanian",
  "Russian",
  // "Samoan",
  // "Scots",
  // "Serbian",
  "Sesotho",
  // "Shona",
  // "Sindhi",
  // "Sinhala",
  // "Slovak",
  // "Slovenian",
  // "Somali",
  "Spanish",
  // "Sundanese",
  // "Swahili",
  // "Swedish",
  "Tamil",
  // "Tatar",
  "Telugu",
  // "Thai",
  // "Turkish",
  // "Turkmen",
  // "Ukrainian",
  "Urdu",
  // "Uyghur",
  // "Uzbek",
  // "Vietnamese",
  // "Welsh",
  // "Xhosa",
  // "Yiddish",
  // "Yoruba",
  // "Zulu"
];

