export const Languages = {
  // af: "Afrikaans",
  // am: "Amharic",
  ar: "Arabic",
  // as: 'Assamese',
  // az: "Azerbaijani",
  // eu: 'Basque',
  // bl: 'Baluchi',
  be: "Belarusian",
  // bg: "Bulgarian",
  bn: "Bengali",
  // bs: "Bosnian",
  // bu: "Burmese",
  // ca: "Catalan",
  // 'zh-CN': 'Chinese(Simplified)',
  // "zh-TW": "Chinese(Traditional)",
  // ceb: "Cebuano",
  // co: "Corsican",
  // hr:'Croatian',
  // cs: "Czech",
  nl: "Dutch",
  // cy: "Welsh",
  // da: "Danish",
  de: "German",
  // el: "Greek",
  en: "English",
  // eo: "Esperanto",
  es: "Spanish",
  // et: "Estonian",
  // fa: "Persian",
  // fl: "Filipino",
  fr: "French",
  // fy: "Frisian",
  // fi: 'Finnish',
  // ga: "Irish",
  gl: "Galician",
  // gd: "Scots Gaelic",
  // he: "Hebrew",
  // haw: "Hawaiian",
  hi: "Hindi",
  // ht: "Haitian",
  // hu: "Hungarian",
  // hy: "Armenian",
  id: "Indonesian",
  // ig: "Igbo",
  // is: "Icelandic",
  // it: "Italian",
  // ja: "Japanese",
  // jv: "Javanese",
  // ka: "Georgian",
  // kk: "Kazakh",
  // km: "Khmer",
  kn: "Kannada",
  // ko: "Korean",
  // ky: "Kyrgyz",
  // la: "Latin",
  // lv: "Latvian",
  // lo: "Lao",
  // lt: "Lithuanian",
  // lb: "Luxembourgish",
  // mk: "Macedonian",
  // mg: "Malagasy",
  ml: "Malayalam",
  // mn: "Mongolian",
  mr: "Marathi",
  // ms: "Malay",
  // mt: "Maltese",
  // my: "Myanmar",
  ne: "Nepali",
  // no: "Norwegian",
  or: "Oriya",
  pa: "Punjabi",
  // pl: "Polish",
  // ps: "Pashto",
  // pt: "Portuguese",
  // rw: "Kinyarwanda",
  // ro: "Romanian",
  ru: "Russian",
  // sd: "Sindhi",
  // si: "Sinhala",
  // sk: "Slovak",
  // sl: "Slovenian",
  // sm: "Samoan",
  // so: "Somali",
  // sq: "Albanian",
  // sr: "Serbian",
  // sw: "Swahili",
  // sv: "Swedish",
  ta: "Tamil",
  te: "Telugu",
  // th: "Thai",
  // tr: "Turkish",
  // tk: "Turkmen",
  // tt: "Tatar",
  // ug: "Uyghur",
  ur: "Urdu",
  // uz: "Uzbek",
  // vi: "Vietnamese",
  // xh: "Xhosa",
  // yi: "Yiddish",
  // yo: "Yoruba",
  // zt: "Zulu",
  gu: 'Gujarati',
  // ha: 'Hausa',
  // hmn: 'Hmong',
  // mi: 'Maori',
  // sn: 'Shona',
  // su: 'Sundanese',
  // uk: 'Ukrainian',
  st: 'Sesotho'
};


export const options = [
  // "Afrikaans",
  // "Albanian",
  // "Amharic",
  "Arabic",
  // "Armenian",
  // "Assamese",
  // "Azerbaijani",
  // "Basque",
  "Belarusian",
  "Bengali",
  // "Bosnian",
  // 'Baluchi',
  // "Bulgarian",
  // "Burmese",
  // "Catalan",
  // "Cebuano",
  // "Chinese(Simplified)",
  // "Chinese(Traditional)",
  // "Corsican",
  // "Croatian",
  // "Czech",
  // "Danish",
  "Dutch",
  "English",
  // "Esperanto",
  // "Estonian",
  // "Filipino",
  // "Finnish",
  "French",
  // "Frisian",
  // "Gaelic",
  "Galician",
  // "Georgian",
  "German",
  // "Greek",
  "Gujarati",
  // "Haitian",
  // "Hausa",
  // "Hawaiian",
  // "Hebrew",
  "Hindi",
  // "Hmong",
  // "Hungarian",
  // "Icelandic",
  // "Igbo",
  "Indonesian",
  // "Irish",
  // "Italian",
  // "Japanese",
  // "Javanese",
  "Kannada",
  // "Kazakh",
  // "Khmer",
  // "Kinyarwanda",
  // "Korean",
  // "Kyrgyz",
  // "Lao",
  // "Latin",
  // "Latvian",
  // "Lithuanian",
  // "Luxembourgish",
  // "Macedonian",
  // "Malagasy",
  // "Malay",
  "Malayalam",
  // "Maltese",
  // "Maori",
  "Marathi",
  // "Mongolian",
  // "Myanmar",
  "Nepali",
  // "Norwegian",
  "Oriya",
  // "Pashto",
  // "Persian",
  // "Polish",
  // "Portuguese",
  "Punjabi",
  // "Romanian",
  "Russian",
  // "Samoan",
  // "Scots",
  // "Serbian",
  "Sesotho",
  // "Shona",
  // "Sindhi",
  // "Sinhala",
  // "Slovak",
  // "Slovenian",
  // "Somali",
  "Spanish",
  // "Sundanese",
  // "Swahili",
  // "Swedish",
  "Tamil",
  // "Tatar",
  "Telugu",
  // "Thai",
  // "Turkish",
  // "Turkmen",
  // "Ukrainian",
  "Urdu",
  // "Uyghur",
  // "Uzbek",
  // "Vietnamese",
  // "Welsh",
  // "Xhosa",
  // "Yiddish",
  // "Yoruba",
  // "Zulu"
];


const uniqueLanguages = [...new Set(Object.values(Languages))];
const sortedLanguages = Object.fromEntries(
  uniqueLanguages
    .sort((a, b) => a.localeCompare(b))
    .map(lang => [Object.keys(Languages).find(key => Languages[key] === lang), lang])
);
export { sortedLanguages };

