

export const Languages = {
  // none: "select language",
  hi: "Hindi",
  en: "English",
  ur: "Urdu",
  ar: "Arabic",
  bn: "Bengali",
  kn: "Kannada",
  ta: "Tamil",
  bg: "Bulgarian",
  ml: "Malayalam",
  ru: "Russian",
  sr: "Serbian",
  uk: "Ukranian",
  hr: "Croatian",
  ga: "Irish",
  sq: "Albanian",
  mr: "Marathi",
  fa: "Persian",
  te: "Telugu",
  tr: "Turkish",
  hu: "Hungarian",
  it: "Italian",
  ro: "Romanian",
  pa: "Punjabi",
  gu: "Gujarati",
  or: "Oriya",
  "zh-CN": "Chinese-Simplified",
  "zh-TW": "Chinese-Traditional",
  ne: "Nepali",
  fr: "French",
  es: "Spanish",
  id: "Indonesian",
  ja: "Japanese",
  jv: "Javanese",
  ko: "Korean",
  be: "Belarusian",
  uz: "Uzbek",
  sd: "Sindhi",
  af: "Afrikaans",
  de: "German",
  is: "Icelandic",
  ig: "Igbo",
  la: "Latin",
  pt: "Portugese",
  th: "Thai",
  su: "Sundanese",
  lo: "Lao",
  si: "Sinhala",
  az: "Azerbaijani",
  kk: "Kazakh",
  mk: "Macedonian",
  bs: "Bosnian",
  ps: "Pashto",
  mg: "Malagasy",
  ms: "Malay",
  yo: "Yoruba",
  cs: "Czech",
  da: "Danish",
  nl: "Dutch",
  no: "Norwegian",
  sl: "Slovenian",
  sv: "Swedish",
  vi: "Vietnamese",
  cy: "Welsh",
  he: "Hebrew",
  km: "Khmer",
  ka: "Georgian",
  mn: "Mongolian",
  ku: "Kurdish",
  ky: "Kyrgyz",
  tk: "Turkmen",
  fi: "Finnish",
  ht: "Haitian Creole",
  haw: "Hawaiian",
  lt: "Lithuanian",
  lb: "Luxembourgish",
  mt: "Maltese",
  pl: "Polish",
  eo: "Esperanto",
  tt: "Tatar",
  ug: "Uyghur",
  ha: "Hausa",
  so: "Somali",
  sw: "Swahili",
  yi: "Yiddish",
  eu: "Basque",
  ca: "Catalan",
  co: "Corsican",
  et: "Estonian",
  fy: "Frisian",
  gl: "Galician",
  hmn: "Hmong",
  rw: "Kinyarwanda",
  lv: "Latvian",
  mi: "Maori",
  sm: "Samoan",
  gd: "Scots Gaelic",
  st: "Sesotho",
  sn: "Shona",
  sk: "Slovak",
  xh: "Xhosa",
  zu: "Zulu",
  ny: "Nyanja",
};
// export const Languages = {
//   hi: "Hindi",
//   en: "English",
//   ur: "Urdu",
//   ar: "Arabic",
//   kn: "Kannada",
//   ta: "Tamil",
//   bg: "Bulgarian",
//   bn: "Bengali",
//   ml: "Malayalam",
//   ru: "Russian",
//   sr: "Serbian",
//   uk: "Ukranian",
//   hr: "Croatian",
//   ga: "Irish",
//   sq: "Albanian",
//   mr: "Marathi",
//   fa: "Persian",
//   te: "Telugu",
//   tr: "Turkish",
//   hu: "Hungarian",
//   it: "Italian",
//   ro: "Romanian",
//   pa: "Punjabi",
//   gu: "Gujarati",
//   or: "Oriya",
//   "zh-CN": "Chinese-Simplified",
//   "zh-TW": "Chinese-Traditional",
//   ne: "Nepali",
//   fr: "French",
//   es: "Spanish",
//   id: "Indonesian",
//   el: "Greek",
//   ja: "Japanese",
//   jv: "Javanese",
//   ko: "Korean",
//   be: "Belarusian",
//   uz: "Uzbek",
//   sd: "Sindhi",
//   af: "Afrikaans",
//   de: "German",
//   is: "Icelandic",
//   ig: "Igbo",
//   la: "Latin",
//   pt: "Portugese",
//   my: "Myanmar",
//   th: "Thai",
//   su: "Sundanese",
//   lo: "Lao",
//   am: "Amharic",
//   si: "Sinhala",
//   az: "Azerbaijani",
//   kk: "Kazakh",
//   mk: "Macedonian",
//   bs: "Bosnian",
//   ps: "Pashto",
//   mg: "Malagasy",
//   ms: "Malay",
//   yo: "Yoruba",
//   cs: "Czech",
//   da: "Danish",
//   nl: "Dutch",
//   tl: "Tagalog",
//   no: "Norwegian",
//   sl: "Slovenian",
//   sv: "Swedish",
//   vi: "Vietnamese",
//   cy: "Welsh",
//   he: "Hebrew",
//   hy: "Armenian",
//   km: "Khmer",
//   ka: "Georgian",
//   mn: "Mongolian",
//   ku: "Kurdish",
//   ky: "Kyrgyz",
//   tk: "Turkmen",
//   fi: "Finnish",
//   ht: "Haitian Creole",
//   haw: "Hawaiian",
//   lt: "Lithuanian",
//   lb: "Luxembourgish",
//   mt: "Maltese",
//   pl: "Polish",
//   eo: "Esperanto",
//   tt: "Tatar",
//   ug: "Uyghur",
//   ha: "Hausa",
//   so: "Somali",
//   sw: "Swahili",
//   yi: "Yiddish",
//   eu: "Basque",
//   ca: "Catalan",
//   ceb: "Cebuano",
//   co: "Corsican",
//   et: "Estonian",
//   fy: "Frisian",
//   gl: "Galician",
//   hmn: "Hmong",
//   rw: "Kinyarwanda",
//   lv: "Latvian",
//   mi: "Maori",
//   sm: "Samoan",
//   gd: "Scots Gaelic",
//   st: "Sesotho",
//   sn: "Shona",
//   sk: "Slovak",
//   xh: "Xhosa",
//   zu: "Zulu",
//   ny: "Nyanja",
//   bu: "Burmese",
//   fl: "Filipino",
// };

const uniqueLanguages = [...new Set(Object.values(Languages))];
const sortedLanguages = Object.fromEntries(
  uniqueLanguages
    .sort((a, b) => a.localeCompare(b))
    .map(lang => [Object.keys(Languages).find(key => Languages[key] === lang), lang])
);
export { sortedLanguages };

